"""Shell completion command for Lilith.

The ``/completion`` command prints (or installs) a shell completion
snippet so users can get tab-completion for the ``lilith`` binary in
bash, zsh, fish and PowerShell.  It is intentionally self-contained:
no subprocesses, no network, no writes outside the user's home
directory.

Usage inside the REPL::

    /completion                  show help + supported shells
    /completion bash             print the bash completion script
    /completion zsh              print the zsh completion script
    /completion fish             print the fish completion script
    /completion powershell       print the PowerShell snippet
    /completion install bash     write to ~/.lilith_completion.bash
                                 and tell the user how to source it
    /completion install zsh      write to ~/.lilith_completion.zsh

The generated snippets are static and small (<3 KB each) — they list
the canonical ``lilith`` subcommands plus every slash command that
``repl._SLASH_COMMANDS`` advertises.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import TYPE_CHECKING

from .render import console, render_error

if TYPE_CHECKING:
    from .agent import AgentSession


_BIN_NAME = "lilith"

# Canonical subcommands exposed by ``lilith`` (the binary itself, not
# the REPL slash set).  Kept short on purpose — these are the ones a
# user typing ``lilith <TAB>`` expects to see.
_BIN_SUBCOMMANDS: list[str] = [
    "prompt",
    "chat",
    "run",
    "init",
    "config",
    "doctor",
    "skills",
    "mcp",
    "providers",
    "models",
    "tools",
    "version",
    "--help",
    "--version",
]


_FALLBACK_SLASH: list[str] = [
    "/tools", "/model", "/provider", "/memory", "/clear", "/cd",
    "/status", "/theme", "/history", "/help", "/quit", "/export",
    "/diff", "/undo", "/redo", "/init", "/plan", "/format", "/lint",
    "/review", "/test", "/completion",
]


def _collect_slash_commands() -> list[str]:
    """Return the canonical slash-command list advertised by the REPL.

    Importing ``repl`` is intentionally deferred so this module stays
    cheap to import even when the REPL never runs (e.g. from the
    sandbox router).  We snapshot the list at call time so any future
    additions to ``_SLASH_COMMANDS`` are reflected automatically.
    """

    try:
        from .repl import _SLASH_COMMANDS
        return list(_SLASH_COMMANDS)
    except Exception:
        return list(_FALLBACK_SLASH)


def _bash_script(commands: list[str]) -> str:
    """Return a portable bash completion script.

    Shell variables inside the script use the literal sequence
    ``${VAR}`` — Python f-strings interpret any unescaped ``{`` as
    the start of a substitution, so we render via ``str.format``
    after escaping the bash ``{`` braces to ``{{``.
    """

    cmds = "\n".join(f"    {c}" for c in commands)
    body = """# bash completion for {bin} -- generated by /completion
# Source from ~/.bashrc:
#   eval "$(lilith completion bash 2>/dev/null || cat ~/.lilith_completion.bash)"

_{binuc}_SLASH=(
{cmds}
)

_{bin}() {{
    local cur prev
    COMPREPLY=()
    cur="${{COMP_WORDS[COMP_CWORD]}}"
    if [[ ${{COMP_CWORD}} -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "${{_{binuc}_SLASH[*]}}" -- "$cur") )
    fi
    return 0
}} && complete -F _{bin} {bin}

# Slash-command completion for the REPL prompt:
_{bin}_slash() {{
    local cur
    cur="${{COMP_WORDS[COMP_CWORD]}}"
    if [[ "$cur" == /* ]]; then
        COMPREPLY=( $(compgen -W "${{_{binuc}_SLASH[*]}}" -- "$cur") )
    fi
}}
"""
    return body.format(bin=_BIN_NAME, binuc=_BIN_NAME.upper(), cmds=cmds)


def _zsh_script(commands: list[str]) -> str:
    """Return a zsh completion script (``#compdef lilith``)."""

    quoted = "\n".join(f"        '{c}'" for c in commands)
    body = """#compdef {bin}
# zsh completion for {bin} -- generated by /completion
# Save to a directory on your $fpath, or:
#   eval "$(lilith completion zsh)"

_{bin}_commands() {{
    local -a commands
    commands=(
{quoted}
    )
    _describe 'command' commands
}}

_{bin}_slash() {{
    local -a slash
    slash=(
{quoted}
    )
    compadd -- "${{slash[@]}}"
}}

_{bin}() {{
    local curcontext="$curcontext" state
    _arguments -C \\
        '1: :->cmd' \\
        '*::arg:->args'

    case $state in
        cmd)
            _{bin}_commands
            ;;
        args)
            if [[ $words[2] == */* || $words[CURRENT-1] == /* ]]; then
                _{bin}_slash
            fi
            ;;
    esac
}}

compdef _{bin} {bin} 2>/dev/null
"""
    return body.format(bin=_BIN_NAME, quoted=quoted)


def _fish_script(commands: list[str]) -> str:
    """Return a fish completion script (``complete -c lilith``)."""

    lines = [
        f"# fish completion for {_BIN_NAME} -- generated by /completion",
        f"# Save to ~/.config/fish/completions/{_BIN_NAME}.fish",
        "",
    ]
    for c in commands:
        lines.append(f"complete -c {_BIN_NAME} -a '{c}'")
    lines.append("")
    return "\n".join(lines) + "\n"


def _powershell_script(commands: list[str]) -> str:
    """Return a PowerShell ``Register-ArgumentCompleter`` snippet."""

    quoted = ",".join(f"'{c}'" for c in commands)
    body = """# PowerShell completion for {bin} -- generated by /completion.
# Add this to your $PROFILE:
#   & (lilith completion powershell | Out-String | Invoke-Expression)

Register-ArgumentCompleter -Native -CommandName '{bin}' -ScriptBlock {{
    param($wordToComplete, $commandAst, $cursorPosition)
    $commands = @({quoted})
    $commands | Where-Object {{ $_ -like "$wordToComplete*" }} | ForEach-Object {{
        [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterName', $_)
    }}
}}
"""
    return body.format(bin=_BIN_NAME, quoted=quoted)


def _install(shell: str, commands: list[str]) -> Path:
    """Write the completion snippet to ``~/.lilith_completion.<ext>``.

    Returns the resolved path.  Raises ``RuntimeError`` on write error.
    """

    ext = {"bash": "bash", "zsh": "zsh", "fish": "fish"}.get(shell)
    if not ext:
        raise RuntimeError(f"install no soportado para {shell!r}")
    home = Path(os.path.expanduser("~"))
    target = home / f".lilith_completion.{ext}"
    script = {
        "bash": _bash_script,
        "zsh": _zsh_script,
        "fish": _fish_script,
    }[shell](commands)
    target.write_text(script, encoding="utf-8")
    return target


async def run_completion_command(session: AgentSession, args: str) -> None:  # noqa: ARG001
    """Entry point wired from ``repl.py``."""

    tokens = args.split()
    sub = tokens[0].lower() if tokens else ""

    commands = _collect_slash_commands()

    if sub in ("", "help", "--help", "-h"):
        console.print(
            "[bold cyan]/completion[/] -- generar script de autocompletado para la shell"
        )
        console.print()
        console.print("  [bold]Uso:[/]")
        console.print("    /completion                mostrar esta ayuda")
        console.print("    /completion bash            imprimir script para bash")
        console.print("    /completion zsh             imprimir script para zsh")
        console.print("    /completion fish            imprimir script para fish")
        console.print("    /completion powershell      imprimir snippet para PowerShell")
        console.print("    /completion install bash    escribir ~/.lilith_completion.bash")
        console.print("    /completion install zsh     escribir ~/.lilith_completion.zsh")
        console.print("    /completion install fish    escribir ~/.lilith_completion.fish")
        console.print()
        console.print(f"  [dim]Comandos publicitados: {len(commands)}[/dim]")
        console.print()
        return

    if sub == "install":
        if len(tokens) < 2:
            render_error("Uso: /completion install <bash|zsh|fish>")
            return
        target_shell = tokens[1].lower()
        try:
            path = _install(target_shell, commands)
        except RuntimeError as exc:
            render_error(str(exc))
            return
        console.print(
            f"[success]✓ Snippet para [bold]{target_shell}[/] escrito en:[/] {path}"
        )
        hint = {
            "bash": f"  echo 'source \"{path}\"' >> ~/.bashrc",
            "zsh": f"  echo 'source \"{path}\"' >> ~/.zshrc",
            "fish": f"  cp {path} ~/.config/fish/completions/{_BIN_NAME}.fish",
        }.get(target_shell)
        if hint:
            console.print(f"  [dim]Activá con: {hint}[/dim]")
        console.print()
        return

    generator = {
        "bash": _bash_script,
        "zsh": _zsh_script,
        "fish": _fish_script,
        "powershell": _powershell_script,
    }.get(sub)

    if generator is None:
        render_error(
            f"Shell desconocida: {sub!r}. Probá bash, zsh, fish, powershell."
        )
        return

    # Plain stdout (no rich markup) -- the snippet will be sourced/eval'd.
    console.print(generator(commands))