"""Compatibility facade for the slash-command handlers.

The handlers live in :mod:`lilith_cli.slash_commands`, grouped by domain.
This module re-exports the names other modules and tests import from it;
patch a handler's dependencies in its own module, not here.
"""

from __future__ import annotations

# ── Comandos utilitarios ────────────────────────────────────────────
# json_commands.py mantiene esta utilidad autocontenida; se reexporta aquí
# para conservar la interfaz pública usada por repl.py y consumidores existentes.
from .json_commands import run_json_command  # noqa: F401

# ── Movidos a metrics_commands.py ─────────────────────────────────
# Se reexportan para no romper los imports existentes.
from .metrics_commands import (  # noqa: F401
    _command_metrics,
    _file_edit_metrics,
    _fmt_secs,
    _format_duration_short,
    _metrics_emit_json,
    _metrics_show_commands,
    _metrics_show_files,
    _metrics_show_summary,
    _metrics_show_tools,
    _telemetry_status,
    _tool_metrics,
    _usage_color,
    run_bench_command,
    run_metrics_command,
    run_tokens_command,
    run_usage_command,
)
from .slash_commands._shared import (  # noqa: F401
    _ERROR_TIPS,
    _FROZEN_EDITOR,
    EDITOR_CONFIG_FILE,
    _format_history_timestamp,
    _get_editor,
    _print_error,
)
from .slash_commands.conversation import (  # noqa: F401
    _CONTEXT_WARN_FILE,
    _GOAL_MARKER,
    _compact_messages,
    _context_snapshot,
    _goal_from_session,
    _load_pin_entries,
    _load_warn_pct,
    _save_warn_pct,
    _stream_agent_reply,
    _truncate_content,
    run_compact_command,
    run_conclave_command,
    run_context_command,
    run_continue_command,
    run_copy_command,
    run_goal_command,
    run_last_tool_command,
    run_pin_command,
    run_recap_command,
    run_redo_command,
    run_summary_command,
)
from .slash_commands.environment import (  # noqa: F401
    _ENV_SNAPSHOT_PATH,
    _env_diff_snapshot,
    _env_snapshot_save,
    _print_env_diff,
    _redact_text,
    _run_deep_checks,
    run_cd_command,
    run_clear_screen_command,
    run_doctor_command,
    run_env_command,
    run_pwd_command,
    run_redact_command,
    run_secret_command,
)
from .slash_commands.extras import (  # noqa: F401
    _LOG_FILE,
    _QR_LAST_FILE,
    _QR_PREFS_FILE,
    _TIMER_STATE,
    _TOUR_STEPS,
    LILITH_TIPS,
    _format_elapsed,
    _speak_text,
    run_feedback_command,
    run_learn_command,
    run_log_command,
    run_qr_command,
    run_timer_command,
    run_tip_command,
    run_tour_command,
    run_voice_command,
)
from .slash_commands.git import (  # noqa: F401
    CHANGELOG_PATH,
    _bump_version,
    _check_patch_targets_in_repo,
    _format_version,
    _parse_changelog_entries,
    _parse_version,
    _pr_compare_url,
    _pr_detect_branch,
    _pr_parse_option_value,
    _prepend_changelog,
    _read_package_version,
    _render_diff_staged_stats,
    _resolve_repo_root,
    _review_summary,
    _run_review_git,
    _write_package_version,
    run_apply_command,
    run_changelog_command,
    run_diff_branch_command,
    run_diff_staged_command,
    run_diff_unstaged_command,
    run_git_command,
    run_pr_command,
    run_release_command,
    run_review_command,
)
from .slash_commands.help import (  # noqa: F401
    run_help_command,
)
from .slash_commands.navigation import (  # noqa: F401
    _SNIPPETS_PATH,
    _compare_diff_files,
    _compare_json_files,
    _compare_recent_paths,
    _compare_text_stats,
    _load_snippets,
    _parse_multi_file_spec,
    _render_todos_table,
    _save_snippets,
    run_compare_command,
    run_deps_command,
    run_explain_command,
    run_map_command,
    run_multi_file_command,
    run_search_command,
    run_snippet_command,
    run_todos_command,
    run_tree_command,
    run_watch_command,
    run_whereami_command,
)
from .slash_commands.quality import (  # noqa: F401
    _DEFAULT_TEST_SUITE,
    _PYTEST_SUMMARY_RE,
    _parse_pytest_summary,
    _render_test_summary,
    _render_test_usage,
    _run_pytest_subprocess,
    _security_scan_file,
    _security_walk,
    _set_test_last_failed_path,
    _validate_test_target,
    run_format_command,
    run_lint_command,
    run_lint_fix_command,
    run_security_command,
    run_test_command,
)
from .slash_commands.sessions import (  # noqa: F401
    _FORKS_DIR,
    _REPLAY_DIR,
    _capture_parse_args,
    _deserialize_session,
    _fork_path,
    _list_forks,
    _serialize_session,
    run_capture_command,
    run_export_command,
    run_file_command,
    run_fork_command,
    run_history_command,
    run_recent_command,
    run_replay_command,
)
from .slash_commands.settings import (  # noqa: F401
    _ALIAS_FILE,
    _DEFAULT_PROFILES,
    _PROFILES_PATH,
    _STREAM_CONFIG_FILE,
    _ensure_profiles,
    _load_aliases,
    _load_profiles,
    _profiles_path,
    _save_aliases,
    _save_profiles,
    run_alias_command,
    run_config_command,
    run_editor_command,
    run_hooks_command,
    run_json_mode_command,
    run_macro_command,
    run_model_info_command,
    run_profile_command,
    run_status_command,
    run_stream_command,
    run_theme_command,
)

# Se movieron a utility_commands.py (grupo autocontenido). Se reexportan
# para no romper los imports existentes de repl.py y de los tests.
from .utility_commands import (  # noqa: F401
    _CALC_BINOPS,
    _CALC_CONSTANTS,
    _CALC_FUNCTIONS,
    _CALC_UNARYOPS,
    _calc_eval_node,
    _extract_text_from_message,
    _now_rfc_value,
    _quote_usage,
    _render_random_usage,
    _resolve_last_assistant_message,
    _resolve_message_by_index,
    _resolve_quote_target,
    calc_eval,
    run_base64_command,
    run_calc_command,
    run_epoch_command,
    run_hash_command,
    run_lines_command,
    run_now_command,
    run_quote_command,
    run_random_command,
    run_reverse_command,
    run_uuid_command,
)
