"""Runestones / artifact helpers for the Lilith IDE.

A Runestone is a self-contained fragment of code, configuration or documentation
forged by Lilith. Users can preview, apply, save or evolve them.
"""

from __future__ import annotations

import dataclasses
import re
import uuid
from pathlib import Path
from typing import Any


@dataclasses.dataclass
class Runestone:
    """A single artifact generated by the agent."""

    id: str
    title: str
    language: str
    content: str
    source: str = ""

    @classmethod
    def from_code_block(cls, language: str, content: str, title: str = "", source: str = "") -> "Runestone":
        """Create a Runestone from a markdown code fence."""
        return cls(
            id=uuid.uuid4().hex[:8],
            title=title or f"runestone-{language}",
            language=language,
            content=content,
            source=source,
        )


def extract_runestones(text: str, source: str = "") -> list[Runestone]:
    """Extract markdown code fences from *text* as Runestones.

    Handles fenced blocks like:

        ```python
        def foo(): ...
        ```

    Returns one Runestone per block. Non-fenced text is ignored.
    """
    pattern = re.compile(r"```(\w*)\n(.*?)\n```", re.DOTALL)
    results: list[Runestone] = []
    for i, (lang, content) in enumerate(pattern.findall(text), start=1):
        lang = lang.strip() or "text"
        title = f"fragment-{i}.{lang}"
        results.append(Runestone.from_code_block(lang, content, title=title, source=source))
    return results


class RunestoneForge:
    """Keep track of Runestones forged during the current session."""

    def __init__(self) -> None:
        self._runestones: dict[str, Runestone] = {}

    def forge(self, text: str, source: str = "") -> list[Runestone]:
        """Extract Runestones from agent output and store them."""
        stones = extract_runestones(text, source=source)
        for stone in stones:
            self._runestones[stone.id] = stone
        return stones

    def get(self, rune_id: str) -> Runestone | None:
        return self._runestones.get(rune_id)

    def list(self) -> list[Runestone]:
        return list(self._runestones.values())

    def remove(self, rune_id: str) -> bool:
        if rune_id in self._runestones:
            del self._runestones[rune_id]
            return True
        return False

    def clear(self) -> None:
        self._runestones.clear()

    def apply(self, rune_id: str, target: Path) -> Path:
        """Write a Runestone to *target* (creating parents as needed)."""
        stone = self._runestones.get(rune_id)
        if not stone:
            raise FileNotFoundError(f"Runestone no encontrado: {rune_id}")
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(stone.content, encoding="utf-8")
        return target

    def to_dict(self) -> dict[str, Any]:
        return {
            rid: dataclasses.asdict(stone)
            for rid, stone in self._runestones.items()
        }
