"""The /help slash command and its curated catalog."""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..session_runtime import SessionRuntime


# Curated /help catalog, grouped by family. Every routed command must appear
# here (see tests/test_help_catalog_*.py).
HELP_CATALOG: dict[str, list[tuple[str, str]]] = {
    "Session": [
        ("clear", "Limpiar historial"),
        ("compact", "Resumir historial [--dry-run --force --keep-last N]"),
        ("history", "Ver historial [--tool <name>]"),
        ("transcript", "Exportar o inspeccionar la transcripción de la sesión"),
        ("undo", "Deshacer última operación"),
        ("undo-peek", "Listar/previsualizar backups pendientes [N | list | clear]"),
        ("redo", "Reenviar el último mensaje al modelo; no rehace archivos"),
        ("retry", "Reenviar último mensaje o enviar uno nuevo [<texto>]"),
        ("save", "Guardar conversación"),
        ("export", "Exportar [--format json|md --output path]"),
        ("bookmark", "Marcadores de conversación [list|go|delete|rename|search]"),
        ("note", "Bloc persistente de notas entre sesiones [list|show|edit|rm|clear]"),
        ("btw", "Pregunta rápida al modelo sin guardar en el historial [<pregunta>]"),
        ("quote", "Citar mensaje del historial como texto plano [N|last|user]"),
        ("copy", "Copiar al portapapeles"),
        ("paste", "Pegar desde el portapapeles y enviar al agente [--prepend TEXTO]"),
        ("quit", "Salir"),
        ("log", "Resumen de sesión [stats|clear|path|N]"),
        ("capture", "Transcripción Markdown [--output <ruta> | --include-tools | --no-usage | --tags <tags> | --exclude-system | --first N | --last N]"),
        ("resume", "Restaurar una conversación guardada"),
        ("continue", "Pedir al agente que continúe su respuesta anterior"),
        ("last-tool", "Detalles de la última tool call"),
        ("pin", "Fijar mensaje al contexto siempre visible"),
        ("clear-screen", "Limpiar terminal sin borrar historial"),
        ("recent", "Archivos editados recientemente [N | clear]"),
        ("goal", "Objetivo persistente de sesión [pause|resume|complete|clear|json]"),
    ],
    "Configuration": [
        ("agent", "Modo del agente [list | nombre]"),
        ("config", "Configuración actual"),
        ("model", "Mostrar/cambiar modelo"),
        ("provider", "Mostrar/cambiar proveedor"),
        ("theme", "Cambiar tema visual [name | current | preview <name> | list]"),
        ("tools", "Habilitar/deshabilitar herramientas"),
        ("profile", "Perfiles de configuración [list|save|show|load|delete]"),
        ("where", "Mostrar qué archivos de configuración se cargaron"),
        ("confirm", "Activar/desactivar confirmación para escrituras destructivas"),
        ("memory", "Buscar o guardar en la memoria persistente [<query> | save <texto>]"),
        ("system", "Mostrar o modificar el system prompt [<nuevo prompt>]"),
    ],
    "Development": [
        ("plan", "Plan numerado de tareas"),
        ("init", "Inicializar proyecto"),
        ("file", "Operaciones de archivo"),
        ("macro", "Macros [record|stop|play|list|stats|show|edit|copy|rename|import|export|validate|delete]"),
        ("batch", "Dispatch de múltiples prompts en secuencia [--continue-on-error]"),
        ("pipeline", "Ejecutar pipeline declarativo desde archivo YAML/JSON"),
        ("workflow", "Ejecutar workflow persistente [list|run|show|delete]"),
        ("template", "Plantillas de prompts"),
        ("lint", "Linting"),
        ("lint-fix", "Auto-fix lints con ruff/black"),
        ("format", "Formatear archivo con ruff/black [--check|--yes]"),
        ("test", "Test runner rápido [path|pattern|last]"),
        ("fork", "Fork de la sesión actual"),
        ("auto", "Modo autónomo"),
        ("todos", "Lista de TODOs persistente"),
        ("review", "Revisión local o sub-agente en segundo plano [--agent status|result]"),
        ("stream", "Estado del streaming de tokens"),
        ("json-mode", "Toggle modo JSON forzado"),
        ("watch", "Re-run de un comando al cambiar archivos"),
        ("bg", "Procesos en background [list|start|status|stop|log|cleanup]"),
        ("editor", "Abrir editor externo para el último patch"),
        ("explain", "Explicar el último comando o tool call"),
    ],
    "Information": [
        ("status", "Estado del ecosistema y proveedor/modelo de sesión"),
        ("cost", "Costo estimado"),
        ("tokens", "Uso de tokens"),
        ("usage", "Estadísticas detalladas"),
        ("metrics", "Métricas agregadas"),
        ("whereami", "Contexto del proyecto (panel)"),
        ("doctor", "Diagnóstico [--fix --deep --json]"),
        ("deps", "Dependencias del proyecto [path|outdated|licenses|help]"),
        ("now", "Timestamp actual"),
        ("epoch", "Conversor Unix timestamp ↔ fecha [ts | YYYY-MM-DD]"),
        ("calc", "Calculadora segura <expresión>"),
        ("state", "Plan de orquestación persistente [show|clear]"),
        ("costs", "Telemetría de delegaciones por preset [reset]"),
        ("skills", "Catálogo de skills de delegación [show|save|delete <name>]"),
        ("kit", "Skills incluidas: list | show NOMBRE; solo lectura"),
        ("capabilities", "Herramientas, límites y token de Windows; no cambia permisos"),
        ("learn", "Minar post-mortems de delegación y sugerir skills [save N]"),
        ("context", "Presupuesto de contexto con barra y umbral [--json]"),
        ("temperature", "Ver o ajustar la temperatura de sampling [valor|reset] [--save]"),
    ],
    "Files & Git": [
        ("cd", "Mostrar/cambiar directorio de trabajo [ruta]"),
        ("pwd", "Mostrar el directorio de trabajo actual"),
        ("git", "Operaciones git"),
        ("diff", "Previsualizar escritura/edición [write | edit], sin aplicar"),
        ("diff-config", "Diff de configuración"),
        ("diff-staged", "Cambios preparadas en git [stats | <archivo>]"),
        ("diff-unstaged", "Cambios sin preparar en git [stats | <archivo>]"),
        ("diff-branch", "Diff HEAD vs ref arbitraria [stats] [<archivo>]"),
        ("apply", "Aplicar un parche unified-diff [--check|--reverse|--3way]"),
        ("tree", "Árbol de archivos"),
        ("map", "Mapa de símbolos (funciones/clases) de un archivo [--depth N]"),
        ("multi-file", "Edit multi-archivo atómico"),
        ("hooks", "Listar/instalar/desinstalar hooks de git"),
        ("release", "Tag + changelog + push de release"),
        ("pr", "Crear PR contra la rama base (gh CLI) [title|body|base|draft]"),
        ("security-review", "Auditar patrones de seguridad en árbol [path] [--json] [--max N]"),
    ],
    "Utilities": [
        ("hash", "MD5/SHA de texto/archivo"),
        ("timer", "Cronómetro y cuenta atrás [start|stop|status|cancel|count N]"),
        ("uuid", "Generar UUIDs v1/v4/v7"),
        ("qr", "Generar códigos QR [--save ruta.png --last]"),
        ("json", "Validar/pretty-print JSON"),
        ("base64", "Encode/decode base64"),
        ("random", "Valores aleatorios criptográficos [int|str|token|bytes|choice]"),
        ("lines", "Contar líneas de archivo"),
        ("reverse", "Invertir texto o líneas"),
        ("alias", "Aliases [set|get|remove|list]"),
        ("tip", "Tips de Lilith [N|list|add|count]"),
        ("compare", "Comparar archivos [files|json|text] <a> <b> | recent <modo>"),
        ("ingest", "Traer una página web al RAG de Mimir [<url> --nombre <slug> --sobrescribir --reindex]"),
        ("search", "Buscar en historial o archivos [history|files <patrón>]"),
        ("snippet", "Guardar/ejecutar snippets reutilizables"),
        ("model-info", "Detalles del modelo activo (precio, contexto, alias)"),
        ("bench", "Medir latencias del proveedor [N iteraciones]"),
        ("redact", "Redactar secretos antes de copiar al portapapeles"),
        ("voice", "TTS toggle [on|off|status|test <texto>]"),
    ],
    "Environment": [
        ("env", "Variables de entorno [NAME | prefix X | snapshot | diff | info | --json]"),
        ("secret", "Secretos de sesión"),
    ],
    "System": [
        ("bifrost", "Estado IPC entre agentes"),
        ("ygg", "Contexto Yggdrasil"),
        ("feedback", "Enviar feedback"),
        ("recap", "Resumen de turnos"),
        ("summary", "Resumen conciso de la conversación"),
        ("replay", "Reproducir interacción"),
        ("subagents", "Listar y probar presets de sub-agentes [test]"),
        ("conclave", "Fan-out de pregunta a 2-4 presets en paralelo [--presets a,b,c]"),
        ("mcp", "Servidores MCP montados en el REPL [list|reload]"),
    ],
    "Orchestration": [
        ("mission", "Estado local de Mission Kernel, corte y recursos de cómputo"),
        ("court", "Corte canónica de Lilith, health de compute y aprendizaje"),
    ],
    "Help": [
        ("help", "Este comando"),
        ("quickstart", "Tour de 30 segundos"),
        ("how", "Cómo usar un slash command [<comando>]"),
        ("completion", "Generar scripts de completion para bash/zsh/fish/powershell"),
        ("tour", "Tour completo"),
        ("commands", "Lista plana de comandos"),
        ("changelog", "Historial [--list | <version>]"),
    ],
}


async def run_help_command(session: SessionRuntime, args: str) -> None:  # noqa: ARG001
    """Show the canonical command discovery surface (/help [query])."""
    from ..command_surface import render_help

    render_help(HELP_CATALOG, args)
