"""Agent coordination and task orchestration."""

from lilith_orchestrator.workflow import (
    GateType,
    OnFailure,
    QualityGate,
    WorkflowDefinition,
    WorkflowEngine,
    WorkflowStep,
    WorkflowResult,
    WorkflowStatus,
    StepResult,
    StepStatus,
    load_workflow,
    load_workflow_file,
)

from lilith_orchestrator.dispatch import TaskDispatcher
from lilith_orchestrator.nl_workflow import NLWorkflowBuilder
from lilith_orchestrator.engine import LilithEngine, EngineUsage
from lilith_orchestrator.tracing import (
    Span,
    SpanKind,
    Trace,
    TraceStore,
    Tracer,
    configure_tracing,
    get_tracer,
    reset_tracer,
)
from lilith_orchestrator.workflow_packages import (
    DEFAULT_ENTRYPOINT,
    PackageLoadError,
    WorkflowPackage,
    WorkflowPackageManifest,
    WorkflowPackageNotFoundError,
    WorkflowPackageRegistry,
    default_workflows_root,
    load_package,
    save_package,
)
from lilith_orchestrator.workflow_validator import (
    ALL_RULES,
    Severity,
    ValidationIssue,
    ValidationReport,
    rule_gate_consistency,
    rule_input_keys_resolvable,
    rule_known_agents,
    rule_no_cycles_in_input_chain,
    rule_orphan_output_keys,
    rule_unique_output_keys,
    rule_unique_step_names,
    rule_unused_variables,
    validate_definition,
    validate_package,
)
from lilith_orchestrator.subagents import (
    MAX_DEPTH as SUBAGENT_MAX_DEPTH,
    SubAgentDefinition,
    SubAgentGuardrails,
    SubAgentResult,
    SubAgentRunner,
    agent_types,
    all_agents as all_subagent_definitions,
    clear_registry as clear_subagent_registry,
    get_agent as get_subagent,
    make_default_definitions,
    register as register_subagent,
    register_defaults as register_default_subagents,
    unregister as unregister_subagent,
)
from lilith_orchestrator.card_bridge import (
    agent_type_for_card,
    card_to_subagent,
    register_card_subagent,
    register_loader_subagents,
    register_vanaheim_subagents,
)
from lilith_orchestrator.agent_router import (
    AgentRoute,
    AgentRouter,
    RouterWeights,
    STOP_WORDS,
    TOOL_HINTS,
    extract_tokens,
    heuristic_tool_hint,
    route_request,
    score_definition,
)

__version__ = "1.12.0"

__all__ = [
    "ALL_RULES",
    "AgentRoute",
    "AgentRouter",
    "DEFAULT_ENTRYPOINT",
    "EngineUsage",
    "GateType",
    "LilithEngine",
    "NLWorkflowBuilder",
    "OnFailure",
    "PackageLoadError",
    "QualityGate",
    "RouterWeights",
    "STOP_WORDS",
    "SUBAGENT_MAX_DEPTH",
    "Severity",
    "Span",
    "SpanKind",
    "StepResult",
    "StepStatus",
    "SubAgentDefinition",
    "SubAgentGuardrails",
    "SubAgentResult",
    "SubAgentRunner",
    "TOOL_HINTS",
    "TaskDispatcher",
    "Trace",
    "TraceStore",
    "Tracer",
    "ValidationIssue",
    "ValidationReport",
    "WorkflowDefinition",
    "WorkflowEngine",
    "WorkflowPackage",
    "WorkflowPackageManifest",
    "WorkflowPackageNotFoundError",
    "WorkflowPackageRegistry",
    "WorkflowResult",
    "WorkflowStatus",
    "WorkflowStep",
    "agent_type_for_card",
    "agent_types",
    "all_subagent_definitions",
    "card_to_subagent",
    "clear_subagent_registry",
    "configure_tracing",
    "default_workflows_root",
    "extract_tokens",
    "get_subagent",
    "get_tracer",
    "heuristic_tool_hint",
    "load_package",
    "load_workflow",
    "load_workflow_file",
    "make_default_definitions",
    "register_card_subagent",
    "register_default_subagents",
    "register_loader_subagents",
    "register_subagent",
    "register_vanaheim_subagents",
    "reset_tracer",
    "route_request",
    "rule_gate_consistency",
    "rule_input_keys_resolvable",
    "rule_known_agents",
    "rule_no_cycles_in_input_chain",
    "rule_orphan_output_keys",
    "rule_unique_output_keys",
    "rule_unique_step_names",
    "rule_unused_variables",
    "save_package",
    "score_definition",
    "unregister_subagent",
    "validate_definition",
    "validate_package",
]  # type: ignore[attr-defined]