"""Lilith Core - Base types, configuration, logging, hooks, governance, and token optimization for Yggdrasil."""

__version__ = "3.4.0"

from lilith_core.governance import (
    GovernanceDecision,
    GovernanceSummary,
    GovernanceSurface,
)

from lilith_core.audit_trail import (
    AuditEntry,
    PolicyAuditTrail,
    make_default_trail,
    summarize_entries,
)
from lilith_core.bus import (
    BusError,
    BusMessage,
    LilithBus,
)
from lilith_core.config import YggdrasilConfig, get_config
from lilith_core.extension_registry import (
    DuplicateExtensionError,
    ExtensionKind,
    ExtensionRegistry,
    ExtensionRegistryError,
    UnknownExtensionError,
)
from lilith_core.goal_state import (
    Gate,
    GateStatus,
    Goal,
    GoalStateManager,
    GoalStatus,
    TodoItem,
    TurnRecord,
)
from lilith_core.hooks import (
    HookContext,
    HookRegistry,
    HookType,
    get_hook_registry,
    register_hook,
)
from lilith_core.logger import get_logger, setup_logger
from lilith_core.policy_engine import (
    AlwaysRule,
    CircuitBreakerRule,
    Policy,
    PolicyAction,
    PolicyEngine,
    PolicyResult,
    PolicyScope,
    PolicyState,
    RateLimitRule,
    RegexRule,
    ResourceLimitRule,
    TokenBudgetRule,
    ToolAllowlistRule,
    ToolDenylistRule,
)
from lilith_core.policy_harness import (
    Decision,
    Expectation,
    HarnessReport,
    PolicyHarness,
    Scenario,
    ScenarioResult,
    to_jsonl,
)
from lilith_core.providers import LLMProvider, LocalProvider
from lilith_core.sandbox import (
    AgentSandbox,
    SandboxAction,
    SandboxError,
    SandboxPolicy,
    SandboxRegistry,
    SandboxRule,
    SandboxRuleType,
    SandboxState,
    SandboxViolation,
    get_sandbox_registry,
)
from lilith_core.sandbox_hooks import (
    activate_sandbox_hooks,
    deactivate_sandbox_hooks,
    get_sandbox_hook_stats,
    sandbox_hooks_active,
)
from lilith_core.token_optimizer import (
    CompressionResult,
    ContextCompressor,
    ResponseCache,
    SemanticCache,
    TokenBudget,
    TokenTracker,
    estimate_messages_tokens,
    estimate_tokens,
)
from lilith_core.tools import (
    CAPABILITY_ONLY,
    CARD_TOOL_ALIASES,
    CARD_TOOL_VOCAB,
    TOOL_NAMES,
    ToolNameValidation,
    canonical_tool_name,
    is_known_card_tool,
    is_real_tool,
    validate_tool_names,
)
from lilith_core.types import Agent, Project, Realm, Service, Status


__all__ = [
    "Agent",
    "AgentSandbox",
    "CAPABILITY_ONLY",
    "CARD_TOOL_ALIASES",
    "CARD_TOOL_VOCAB",
    "DuplicateExtensionError",
    "ExtensionKind",
    "ExtensionRegistry",
    "ExtensionRegistryError",
    "GovernanceDecision",
    "GovernanceSummary",
    "GovernanceSurface",
    "AlwaysRule",
    "AuditEntry",
    "BusError",
    "BusMessage",
    "CircuitBreakerRule",
    "CompressionResult",
    "ContextCompressor",
    "Decision",
    "Expectation",
    "ExtensionRegistryError",
    "Gate",
    "GateStatus",
    "Goal",
    "GoalStateManager",
    "GoalStatus",
    "HarnessReport",
    "HookContext",
    "HookRegistry",
    "HookType",
    "LLMProvider",
    "LilithBus",
    "LocalProvider",
    "Policy",
    "PolicyAction",
    "PolicyAuditTrail",
    "PolicyEngine",
    "PolicyHarness",
    "PolicyResult",
    "PolicyScope",
    "PolicyState",
    "Project",
    "RateLimitRule",
    "Realm",
    "RegexRule",
    "ResourceLimitRule",
    "ResponseCache",
    "SandboxAction",
    "SandboxError",
    "SandboxPolicy",
    "SandboxRegistry",
    "SandboxRule",
    "SandboxRuleType",
    "SandboxState",
    "SandboxViolation",
    "Scenario",
    "ScenarioResult",
    "SemanticCache",
    "Service",
    "Status",
    "TOOL_NAMES",
    "TokenBudget",
    "TokenBudgetRule",
    "TokenTracker",
    "ToolAllowlistRule",
    "ToolDenylistRule",
    "ToolNameValidation",
    "UnknownExtensionError",
    "YggdrasilConfig",
    "activate_sandbox_hooks",
    "canonical_tool_name",
    "deactivate_sandbox_hooks",
    "estimate_messages_tokens",
    "estimate_tokens",
    "get_config",
    "get_hook_registry",
    "get_logger",
    "get_sandbox_hook_stats",
    "get_sandbox_registry",
    "is_known_card_tool",
    "is_real_tool",
    "make_default_trail",
    "register_hook",
    "sandbox_hooks_active",
    "setup_logger",
    "summarize_entries",
    "TodoItem",
    "to_jsonl",
    "TurnRecord",
    "validate_tool_names",
]  # noqa: E501